import { useMutation, useQuery, useQueryClient } from 'react-query';
import {
  anyUsers,
  createAppointment,
  createBarber,
  CreateBarberDto,
  createBarberService,
  CreateBarberServiceDto,
  createFirstUser,
  createUser,
  createUserDto,
  deleteBarber,
  getAppointments,
  getAppointmentsCount,
  GetAppointmentsRequestParams,
  getBarber,
  getBarbers,
  getBarberService,
  getBarberServices,
  GetBarberServicesRequestParams,
  GetBarbersRequestParams,
  getUserRoles,
  getUsers,
  GetUsersRequestParams,
  updateBarber,
  UpdateBarberDto,
  UpdateBarberSerivceDto,
  updateBarberService,
} from './api';
import { useAuth } from './components/auth/AuthContext';

